//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno
    {
        public Aluno()
        {
            this.Chamadas = new HashSet<Chamada>();
        }
    
        public long alunoUID { get; set; }
        public long turmaUID { get; set; }
        public long pessoaUID { get; set; }
        public bool ativo { get; set; }
        public System.DateTime dataCriacao { get; set; }
    
        public virtual Turma Turma { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual ICollection<Chamada> Chamadas { get; set; }
    }
}
