//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtividadeAula
    {
        public long atividadeaulaUID { get; set; }
        public bool ativa { get; set; }
        public long aulaUID { get; set; }
        public string titulo { get; set; }
        public string descricao { get; set; }
        public int duracaoMin { get; set; }
        public bool aprovado { get; set; }
        public int ordem { get; set; }
    
        public virtual Aula Aula { get; set; }
    }
}
