//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chamada
    {
        public long chamadaUID { get; set; }
        public long aulaUID { get; set; }
        public long alunoUID { get; set; }
        public bool presente { get; set; }
        public Nullable<long> justificativaaulaUID { get; set; }
        public bool ativa { get; set; }
    
        public virtual Aluno Aluno { get; set; }
        public virtual Aula Aula { get; set; }
        public virtual JustificativaAula JustificativaAula { get; set; }
    }
}
