//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChaveAtivacao
    {
        public ChaveAtivacao()
        {
            this.Permissaos = new HashSet<Permissao>();
        }
    
        public long chaveAtivacaoUID { get; set; }
        public System.DateTime dataCriacao { get; set; }
        public string cpf { get; set; }
        public int tipoPermissao { get; set; }
        public string email { get; set; }
        public long usuarioUID { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Permissao> Permissaos { get; set; }
    }
}
