//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public int cursoUID { get; set; }
        public string nome { get; set; }
        public long cargaHoraria { get; set; }
        public int turma { get; set; }
        public bool ativo { get; set; }
    }
}
