//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaSemanaHabito
    {
        public DiaSemanaHabito()
        {
            this.HorariosHabito = new HashSet<HorarioHabito>();
        }
    
        public long diaSemanaHabitoUID { get; set; }
        public long habitoUID { get; set; }
        public bool Ativo { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public int DiaSemana { get; set; }
        public int Ordem { get; set; }
        public bool Finalizado { get; set; }
    
        public virtual Habito Habito { get; set; }
        public virtual ICollection<HorarioHabito> HorariosHabito { get; set; }
    }
}
