//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaSemanaTurma
    {
        public DiaSemanaTurma()
        {
            this.Aulas = new HashSet<Aula>();
        }
    
        public long diasemanaturmaUID { get; set; }
        public bool ativo { get; set; }
        public long turmaUID { get; set; }
        public int diaSemanal { get; set; }
    
        public virtual ICollection<Aula> Aulas { get; set; }
        public virtual Turma Turma { get; set; }
    }
}
