//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecucaoMeta
    {
        public ExecucaoMeta()
        {
            this.AnotacaoExecucaoMetas = new HashSet<AnotacaoExecucaoMeta>();
            this.RegistroSituacaoExecucaoMetas = new HashSet<RegistroSituacaoExecucaoMeta>();
        }
    
        public long execucaoMetaUID { get; set; }
        public long metaUID { get; set; }
        public int ordemPasso { get; set; }
        public string descricao { get; set; }
        public System.DateTime dataInicio { get; set; }
        public System.DateTime dataTermino { get; set; }
        public bool ativo { get; set; }
        public string tema { get; set; }
        public int situacao { get; set; }
        public Nullable<long> atividadeFixaUID { get; set; }
    
        public virtual ICollection<AnotacaoExecucaoMeta> AnotacaoExecucaoMetas { get; set; }
        public virtual AtividadeFixa AtividadeFixa { get; set; }
        public virtual Meta Meta { get; set; }
        public virtual ICollection<RegistroSituacaoExecucaoMeta> RegistroSituacaoExecucaoMetas { get; set; }
    }
}
