//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GatilhoHabito
    {
        public long gatilhoHabitoUID { get; set; }
        public long habitoUID { get; set; }
        public bool ativo { get; set; }
        public bool finalizado { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public System.DateTime DataAlteracao { get; set; }
        public int OrdemExecucao { get; set; }
        public int TempoEspera { get; set; }
    
        public virtual Habito Habito { get; set; }
    }
}
