//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habito
    {
        public Habito()
        {
            this.CiclosHabito = new HashSet<CicloHabito>();
            this.DiasSemanaHabito = new HashSet<DiaSemanaHabito>();
            this.GatilhosHabito = new HashSet<GatilhoHabito>();
        }
    
        public long habitoUID { get; set; }
        public long metaUID { get; set; }
        public bool ativo { get; set; }
        public bool finalizado { get; set; }
        public int TipoGatilho { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public System.DateTime DataAlteracao { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<CicloHabito> CiclosHabito { get; set; }
        public virtual ICollection<DiaSemanaHabito> DiasSemanaHabito { get; set; }
        public virtual ICollection<GatilhoHabito> GatilhosHabito { get; set; }
        public virtual Meta Meta { get; set; }
    }
}
