//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioHabito
    {
        public HorarioHabito()
        {
            this.ExecucaoMetas = new HashSet<ExecucaoMeta>();
        }
    
        public long horarioHabitoUID { get; set; }
        public Nullable<long> diaSemanaHabitoUID { get; set; }
        public Nullable<long> cicloHabitoUID { get; set; }
        public bool Ativo { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public bool Finalizado { get; set; }
        public System.TimeSpan HorarioInicio { get; set; }
        public System.TimeSpan HorarioTermino { get; set; }
    
        public virtual CicloHabito CicloHabito { get; set; }
        public virtual DiaSemanaHabito DiaSemanaHabito { get; set; }
        public virtual ICollection<ExecucaoMeta> ExecucaoMetas { get; set; }
    }
}
