//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JustificativaAula
    {
        public long justificativaaulaUID { get; set; }
        public long chamadaUID { get; set; }
        public bool ativa { get; set; }
        public string justificativa { get; set; }
        public bool aprovadaCoordenador { get; set; }
    
        public virtual Chamada Chamada { get; set; }
    }
}
