//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JustificativaAula
    {
        public JustificativaAula()
        {
            this.Chamadas = new HashSet<Chamada>();
        }
    
        public long justificativaaulaUID { get; set; }
        public long alunoUID { get; set; }
        public long aulaUID { get; set; }
        public bool ativa { get; set; }
        public string justificativa { get; set; }
        public bool aprovadaCoordenador { get; set; }
    
        public virtual Aluno Aluno { get; set; }
        public virtual Aula Aula { get; set; }
        public virtual ICollection<Chamada> Chamadas { get; set; }
    }
}
