//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int loginUID { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
        public System.DateTime validade { get; set; }
        public long pessoaUID { get; set; }
    }
}
