//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meta
    {
        public Meta()
        {
            this.ExecucaoMetas = new HashSet<ExecucaoMeta>();
        }
    
        public long metaUID { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> dataObjetivo { get; set; }
        public Nullable<System.DateTime> dataInicio { get; set; }
        public string motivo { get; set; }
        public bool ativo { get; set; }
        public int ordemPrioridade { get; set; }
    
        public virtual ICollection<ExecucaoMeta> ExecucaoMetas { get; set; }
    }
}
