//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModalidadeSet
    {
        public ModalidadeSet()
        {
            this.TurmaSet1 = new HashSet<TurmaSet>();
        }
    
        public long modalidadeUID { get; set; }
        public string Modalidade { get; set; }
        public string Descricao { get; set; }
        public double ValorInscrição { get; set; }
        public double ValorMensalidade { get; set; }
        public bool ativa { get; set; }
        public bool disponivel { get; set; }
        public int tipoModalidade { get; set; }
    
        public virtual ICollection<TurmaSet> TurmaSet1 { get; set; }
    }
}
