//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modalidade
    {
        public Modalidade()
        {
            this.Turmas = new HashSet<Turma>();
        }
    
        public long modalidadeUID { get; set; }
        public int tipoModalidade { get; set; }
        public string nome { get; set; }
        public string Descricao { get; set; }
        public double ValorInscrição { get; set; }
        public double ValorMensalidade { get; set; }
        public bool ativa { get; set; }
        public bool disponivel { get; set; }
    
        public virtual ICollection<Turma> Turmas { get; set; }
    }
}
