//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permissao
    {
        public long permissaoUID { get; set; }
        public bool ativo { get; set; }
        public System.DateTime dataCriacao { get; set; }
        public int tipoPermissao { get; set; }
        public long chaveAtivacaoUID { get; set; }
        public long usuarioUID { get; set; }
    
        public virtual ChaveAtivacao ChaveAtivacao { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
