//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public Pessoa()
        {
            this.Alunoes = new HashSet<Aluno>();
            this.Autonomoes = new HashSet<Autonomo>();
            this.Coordenadors = new HashSet<Coordenador>();
            this.Logins = new HashSet<Login>();
            this.Permissaos = new HashSet<Permissao>();
            this.Bolsistas = new HashSet<Bolsista>();
            this.Professors = new HashSet<Professor>();
        }
    
        public long pessoaUID { get; set; }
        public string nome { get; set; }
        public string cpf { get; set; }
        public System.DateTime nascimento { get; set; }
        public string endereco { get; set; }
        public string telefone { get; set; }
        public int nivelAcesso { get; set; }
    
        public virtual ICollection<Aluno> Alunoes { get; set; }
        public virtual ICollection<Autonomo> Autonomoes { get; set; }
        public virtual ICollection<Coordenador> Coordenadors { get; set; }
        public virtual ICollection<Login> Logins { get; set; }
        public virtual ICollection<Permissao> Permissaos { get; set; }
        public virtual ICollection<Bolsista> Bolsistas { get; set; }
        public virtual ICollection<Professor> Professors { get; set; }
    }
}
