//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professor
    {
        public Professor()
        {
            this.ProfessorTurmas = new HashSet<ProfessorTurma>();
        }
    
        public long professorUID { get; set; }
        public Nullable<long> bolsistaUID { get; set; }
        public Nullable<long> coordenadorUID { get; set; }
        public Nullable<long> autonomoUID { get; set; }
        public bool ativo { get; set; }
        public System.DateTime validade { get; set; }
    
        public virtual Autonomo Autonomo { get; set; }
        public virtual Bolsista Bolsista { get; set; }
        public virtual Coordenador Coordenador { get; set; }
        public virtual ICollection<ProfessorTurma> ProfessorTurmas { get; set; }
    }
}
