//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubTipoMeta
    {
        public SubTipoMeta()
        {
            this.Metas = new HashSet<Meta>();
        }
    
        public int subTipoMetaUID { get; set; }
        public int tipo { get; set; }
        public string nome { get; set; }
        public bool ativo { get; set; }
        public System.DateTime dataCriacao { get; set; }
    
        public virtual ICollection<Meta> Metas { get; set; }
    }
}
