//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurmaSet
    {
        public long turmaUID { get; set; }
        public System.DateTime HorarioInicio { get; set; }
        public double DuracaoAula { get; set; }
        public string Descricao { get; set; }
        public int Vagas { get; set; }
        public bool ativa { get; set; }
        public bool disponivel { get; set; }
        public long modalidadeUID { get; set; }
    
        public virtual ModalidadeSet Modalidade { get; set; }
    }
}
