//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.ChavesAtivacao = new HashSet<ChaveAtivacao>();
            this.Permissoes = new HashSet<Permissao>();
            this.Metas = new HashSet<Meta>();
        }
    
        public long usuarioUID { get; set; }
        public string cpf { get; set; }
        public string senha { get; set; }
        public string senhaSecundaria { get; set; }
        public string email { get; set; }
        public bool ativo { get; set; }
        public System.DateTime dataCriacao { get; set; }
        public string nome { get; set; }
    
        public virtual ICollection<ChaveAtivacao> ChavesAtivacao { get; set; }
        public virtual ICollection<Permissao> Permissoes { get; set; }
        public virtual ICollection<Meta> Metas { get; set; }
    }
}
